### ISSUE TITLE
[QUESTION] 404: Not found in the terminal

### ISSUE THREAD

**Issue by giulianok** [americanexpress/one-app#36]
I cloned **One App** and created an empty One Module from the Yeoman Generator. The `localhost:3000` is rendering "Welcome to One App", looks like it's working fine, but I'm getting this error in the terminal, not sure why:

```
➜  one-app git:(master) npm start -- --root-module-name=one-module

> @americanexpress/one-app@5.0.0-rc1 start /Users/giulianokranevitter/Projects/Tests/one-app
> node lib/server/index.js "--root-module-name=one-module"

log: one-app-dev-cdn only using locally served modules
✔ 👕 one-app-dev-cdn server listening on port 3001
✔ 👖 one-app-dev-proxy server listening on port 3002
✔ 📊 Metrics server listening on port 3005
✔ 🌎 One App server listening on port 3000
✔ Polled Holocron Module map: no updates (polling again in 7s)
✔ Polled Holocron Module map: no updates (polling again in 9s)
✔ Polled Holocron Module map: no updates (polling again in 11s)
warn: CSP Violation: undefined:undefined:undefined on page http://localhost:3000/ violated the font-src policy via data
error: [
  {
    msg: '404: Not found',
    stack: 'Error: 404: Not found\n' +
      '    at Object.onEnter (/Users/giulianokranevitter/Projects/Tests/one-app/lib/universal/routes.js:49:62)\n' +
      '    at Array.transitionHook (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:48:12)\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:119:19\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:89:7\n' +
      '    at next (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/AsyncUtils.js:39:12)\n' +
      '    at loopAsync (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/AsyncUtils.js:56:3)\n' +
      '    at runTransitionHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:88:31)\n' +
      '    at runEnterHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:112:12)\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/createTransitionManager.js:95:7\n' +
      '    at runTransitionHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:79:7)',
    href: undefined,
    otherData: {
      location: [Object],
      code: 404,
      collectionMethod: 'applicationError'
    }
  }
]
✔ Polled Holocron Module map: no updates (polling again in 17s)
✔ Polled Holocron Module map: no updates (polling again in 23s)
✔ Polled Holocron Module map: no updates (polling again in 30s)
✔ Polled Holocron Module map: no updates (polling again in 37s)



```

**Comment by 10xLaCroixDrinker** [comment]
Can you take a look at `otherData.location` and see if you recognize the route?

**Comment by giulianok** [comment]
> Can you take a look at `otherData.location` and see if you recognize the route?

I'm having a hard time to locate how and where is logging the error to stringify the object

**Comment by giulianok** [comment]
@10xLaCroixDrinker found the origin of the report, `one-app-ducks` (a bit annoying not knowing where the error is coming from, a multi-package repo with lerna would be useful).

This is the log
```
error: [
  {
    msg: '404: Not found',
    stack: 'Error: 404: Not found\n' +
      '    at Object.onEnter (/Users/giulianokranevitter/Projects/Tests/one-app/lib/universal/routes.js:49:62)\n' +
      '    at Array.transitionHook (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:48:12)\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:119:19\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:89:7\n' +
      '    at next (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/AsyncUtils.js:39:12)\n' +
      '    at loopAsync (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/AsyncUtils.js:56:3)\n' +
      '    at runTransitionHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:88:31)\n' +
      '    at runEnterHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:112:12)\n' +
      '    at /Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/createTransitionManager.js:95:7\n' +
      '    at runTransitionHooks (/Users/giulianokranevitter/Projects/Tests/one-app/node_modules/@americanexpress/one-app-router/lib/TransitionUtils.js:79:7)',
    href: undefined,
    otherData: '{"location":{"pathname":"/favicon.ico","search":"","hash":"","action":"POP","key":"izc9g9","query":{}},"code":404,"collectionMethod":"applicationError"}'
  }
]
```

**Comment by JamesSingleton** [comment]
So I ran into this issue later and what I did was `rm -rf node_modules && npm i` and I no longer had that issue. It happened when I pulled down `one-app`. Can you give that a try?

**Comment by giulianok** [comment]
@JamesSingleton just did that and still happening (only when I hit the root `http://localhost:3000`)

**Comment by 10xLaCroixDrinker** [comment]
It's a default behavior from your browser to look there when you don't declare the favicon's location, which you could do with `react-helmet`.

Can either of you open a PR to stringify `otherData` so these logs are easier to read?

**Comment by JamesSingleton** [comment]
So not sure if @giulianok is on a Mac or Windows, but when I run this on my Windows machine, I get the following upon `npm start -- --root-module-name=my-root-module`:
```
error: [
  {
    msg: '404: Not found',
    stack: 'Error: 404: Not found\n' +
      '    at Object.onEnter (D:\\Coding\\my-apartment\\one-app\\lib\\universal\\routes.js:49:62)\n' +
      '    at Array.transitionHook (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:48:12)\n' +
      '    at D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:119:19\n' +
      '    at D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:89:7\n' +
      '    at next (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\AsyncUtils.js:39:12)\n' +
      '    at loopAsync (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\AsyncUtils.js:56:3)\n' +
      '    at runTransitionHooks (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:88:31)\n' +
      '    at runEnterHooks (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:112:12)\n' +
      '    at D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\createTransitionManager.js:95:7\n' +
      '    at runTransitionHooks (D:\\Coding\\my-apartment\\one-app\\node_modules\\@americanexpress\\one-app-router\\lib\\TransitionUtils.js:79:7)',
    href: undefined,
    otherData: {
      location: [Object],
      code: 404,
      collectionMethod: 'applicationError'
    }
  }
]
```

With a root module that has a `childRoutes.jsx` that looks like

```
import React from 'react';
import ModuleRoute from 'holocron-module-route';

const childRoutes = () => ([
  <ModuleRoute moduleName="one-app-page-wrapper" header="my-apartment-header" footer="my-apartment-footer" className="my-class-name">
    <ModuleRoute path="/search" moduleName="my-apartment-search-results" />
  </ModuleRoute>,
]);

export default childRoutes;
```

The error just keeps repeating even when I am not on http://localhost:3000

**Comment by JamesSingleton** [comment]
@10xLaCroixDrinker,

Are you ok if the the `otherData` comes back like this? If so, I will make a PR to `one-app-ducks`

```
otherData: '{"location":{"pathname":"/socket.io/","search":"?X_LOCAL_SECURITY_COOKIE=&EIO=3&transport=polling&t=1582167928319-11855","hash":"","action":"POP","key":"z7pzuy","query":{"EIO":"3","X_LOCAL_SECURITY_COOKIE":"","t":"1582167928319-11855","transport":"polling"}},"code":404,"collectionMethod":"applicationError"}' 
```

This is what I am getting which is due to Nvidia's GameStream hitting that port for some reason.
